### ISSUE TITLE
Branch upstream_gzdoom_stereo3D : compilation error

### ISSUE THREAD

**Issue by dethegeek** [cmbruns/gz3doom#107]
Hi

I'm trying to compile the above mentinned branch to test your pull request to gzdoom repository. Compilation failed due to a probably missing header file.

Compilation of the master branch of gzdoom works flawlessly.

Here is the error : 

```
In file included from /home/dethegeek/gzdoom-stereo/gz3doom/src/./gl/stereo3d/gl_stereo3d.h:5:0,
                 from /home/dethegeek/gzdoom-stereo/gz3doom/src/gl/stereo3d/gl_stereo_cvars.cpp:1:
/home/dethegeek/gzdoom-stereo/gz3doom/src/./gl/data/gl_matrix.h: In member function ‘void VSMatrix::copy(FLOATTYPE*)’:
/home/dethegeek/gzdoom-stereo/gz3doom/src/./gl/data/gl_matrix.h:66:49: error: ‘memcpy’ was not declared in this scope
    memcpy(pDest, mMatrix, 16 * sizeof(FLOATTYPE));
                                                 ^
/home/dethegeek/gzdoom-stereo/gz3doom/src/gl/stereo3d/gl_stereo_cvars.cpp: At global scope:
/home/dethegeek/gzdoom-stereo/gz3doom/src/gl/stereo3d/gl_stereo_cvars.cpp:17:58: error: ‘nullptr’ was not declared in this scope
 Stereo3DMode const * Stereo3DMode::currentStereo3DMode = nullptr;
                                                          ^
src/CMakeFiles/zdoom.dir/build.make:6437: recipe for target 'src/CMakeFiles/zdoom.dir/gl/stereo3d/gl_stereo_cvars.o' failed
```

The system system is a 64 bits Debian Testing.

I'll search for a fix, but the GZDoom's code is unknown to me, then you'll very likely fix this faster than me :)

**Comment by cmbruns** [comment]
Unfortunately I don't have my linux dev environment spun up at the moment.
Could you try adding "#include <cstring>" to the include section at the top of file gl_stereo_cvars.cpp, and let us know if that resolves or changes the compile error?

**Comment by dethegeek** [comment]
Just tried to add #include <string.h>. The first error has been solved this way.

Now the second one...

**Comment by cmbruns** [comment]
The second one could maybe be resolved by changing "nullptr" to "0" (zero). That is, changing
"Stereo3DMode const * Stereo3DMode::currentStereo3DMode = nullptr;"
to 
"Stereo3DMode const * Stereo3DMode::currentStereo3DMode = 0;"

**Comment by dethegeek** [comment]
With this ugly fix the compilation succeeds and I'm able to switch between various VR modes.

I guess you'll fix these errors a smarter way soon :)

Thank you.

**Comment by cmbruns** [comment]
Thank you for testing this. I just now committed some changes to the branch upstream_gzdoom_stereo3d that should fix these compile errors. Would you be able to test and verify that the changes work for you?

**Comment by dethegeek** [comment]
make clean && make -j 8 && ./gzdoom => success !

**Comment by cmbruns** [comment]
Awesome. Thanks for reporting and testing. I'm closing this issue now.
