### ISSUE TITLE
Head/neck based view positioning

### ISSUE THREAD

**Issue by Blastfrog** [cmbruns/gz3doom#109]
It feels weird in VR when your view stays in the same place as you turn your head around. See Doom 3 BFG edition for how to handle this.

**Comment by cmbruns-hhmi** [comment]
I don't understand. Please describe the problem in greater detail.

**Comment by Blastfrog** [comment]
In real life, when you move your head, the position of your eyes relative to the rest of your body does not stay the same, unlike most FPS games.

Picture it like clock hands representing a side profile of a person. The very center of the clock is the base of the neck, the end of the clock hand is where your eyes are. 12 o'clock is where they'd be when looking all the way up, 1:30 when looking straight forward, and 3 o'clock when looking straight down.

Roll needs to be taken into account too for the same reasons.

See line 8971 here: https://github.com/id-Software/DOOM-3-BFG/blob/1caba1979589971b5ed44e315d9ead30b278d8b4/neo/d3xp/Player.cpp

**Comment by cmbruns-hhmi** [comment]
Thanks for the clarification.

It seems to me, that in the case of the DK2, with the head position tracking camera on, this effect is already taken account of in the measured positional tracking.

In the case of the DK1, the effect should be accounted by the neck model effect on position tracking. Are you using a DK1? In the Oculus Configuration Utility, under the "Advanced" section, do you have neck model parameters set to reasonable values? If so, are you telling me that when you are, say, facing close to a wall, and you roll your head to the right, say, that you do not perceive your viewpoint also shifting a bit to the right?

Because it totally works for me. What headset are you using? What version of GZ3Doom are you running? What version of the Oculus Runtime do you have installed.

**Comment by cmbruns-hhmi** [comment]
I think this might be the same as issue #11 

In that issue, I noted that it was necessary to slightly change the neck model parameters, to get them to work at all. At least on the DK1 with SDK 0.4. But it seems to be working for me without changing those parameters with a new computer on which I do not recall having changed the neck parameters yet.

**Comment by Blastfrog** [comment]
I use the latest stable GZ3Doom with a DK1 on runtime 0.8.

"under the "Advanced" section, do you have neck model parameters set to reasonable values?"
There are no such settings that I can find. I think might need to be handled game-side.

"when you are, say, facing close to a wall, and you roll your head to the right, say, that you do not perceive your viewpoint also shifting a bit to the right?"
No such thing occurs for me.

**Comment by Blastfrog** [comment]
I messed with it a bit more, it actually is there but is so minor it's nearly unnoticeable. If it's relying on the Oculus settings, I suppose this issue can be closed.

**Comment by cmbruns** [comment]
![config_util_neck](https://cloud.githubusercontent.com/assets/2649705/12213116/c337f144-b640-11e5-80da-55bb16122c6f.png)

If you change the values in the neck model, does it change the size of the viewpoint shift you see?

In the doom console, is the value of vr_ipd roughly 0.062?
Is the value if vr_player_height_meters roughly 2.0?

**Comment by Blastfrog** [comment]
1. Yes.
2. Yes.
3. No, it's 1.75 instead. 2.0 sounds pretty high, that's approximately 6' 7".

**Comment by cmbruns** [comment]
Oops. Of course you are right. I'm not sure why I have my height set to 2.

So it seems the SDK/GZ3Doom is reading the values and using them. But perhaps the scaling is wrong in some way. This sort of problem is difficult to investigate. I remember at one point, I had a meter stick out, and would slide the DK2 headset along it, and make sure the positional change in the doom world matches my expectations. Perhaps I should conduct a similar study with the DK1 and translation-from-rotation.

**Comment by Blastfrog** [comment]
I've done a bit of research into Doom's scale. 8 units per foot vertically is what id used (see the 0.4 alpha readme file). Due to the 5:6 ratio pixels, that means 9.6 units horizontally are a foot.

Perhaps you should have a console variable like "vr_units_per_vertical_foot" that defaults to 8? The horizontal should be automatically calculated based on the MAPINFO property "pixelratio".

**Comment by cmbruns-hhmi** [comment]
@Blastfrog The world scale is already computed in GZ3Doom using the CVAR  vr_player_height_meters. 

This issue, if still present, only affects the DK1 headset. As that headset is completely unsupported in the latest 1.3 SDK/runtime, I'm closing this issue as WONTFIX.
