### ISSUE TITLE
Implement neck model

### ISSUE THREAD

**Issue by cmbruns** [cmbruns/gz3doom#11]
To make head rotations look just so.

**Comment by cmbruns-hhmi** [comment]
See this thread, which might help getting neck model working on DK1 with SDK 0.3
https://forums.oculus.com/viewtopic.php?t=9824

**Comment by cmbruns** [comment]
To get the neck model working with the DK1 and service 0.4.2, you need to open the configuration utility and slightly change the neck model parameters. Otherwise, the neck model parameters do not work.

**Comment by cmbruns** [comment]
Fixed in revision cf54af795821ae3585955d65dc7ed33e93be72ce
