### ISSUE TITLE
Bleeding flat render behavior inconsistent between eyes

### ISSUE THREAD

**Issue by Blastfrog** [cmbruns/gz3doom#110]
If there is a bleeding flat, the left eye will not draw it at all, and the right eye will not only draw it, but extend past where it's supposed to.

I think a screenshot would better demonstrate what I'm talking about. Is there a way to take a screenshot of the raw Oculus image?

**Comment by cmbruns** [comment]
I suppose you tried the regular screenshot command and it did not work in Rift Mode?
Do you see the effect on the desktop monitor view?
Do you see the same effect in vr_mode 3?

**Comment by Blastfrog** [comment]
vr_mode 3 is slightly less broken than vr_mode 8, but still has problems.
http://i.imgur.com/odtjjry.png

This is a cellphone camera image of the right eye of my DK1 in Strife.
http://i.imgur.com/lRmhjNX.jpg

**Comment by cmbruns** [comment]
@Blastfrog do you think this could be the same problem as in issue #40 ?

**Comment by cmbruns** [comment]
The first image in the earlier comment http://i.imgur.com/odtjjry.png clearly shows a gap in the platform below the rising window in the left eye, but not in the right eye. (I'm not sure what the problem in the second image is supposed to be.)

**Comment by cmbruns** [comment]
Very likely fixed in revision a88130b0bf275f263b2e6a29b7b1387947270dc5.

**Comment by cmbruns** [comment]
@Blastfrog Would you be able to test the latest version to verify if this problem is fixed?
https://github.com/cmbruns/gz3doom/releases

**Comment by cmbruns** [comment]
Closing as this is most likely fixed, and no response from original reporter.
