### ISSUE TITLE
Screen effects should affect entire screen

### ISSUE THREAD

**Issue by cmbruns-hhmi** [cmbruns/gz3doom#112]
As of 1.8.10_d, screen effects such the green radiation suit, red berserk pack, and red "hurt" flash, occupy a rectangle around the weapon.

Better would be to decouple those effects from the weapon display, and apply them to the entire 3D scene.

**Comment by cmbruns** [comment]
Fixed in revision 2b41c73975162ba967ac2c3f52b7fcac712e57ec
