### ISSUE TITLE
Remove Cmake warnings in recent Cmake

### ISSUE THREAD

**Issue by ckbruns** [cmbruns/gz3doom#119]
CMake Warning (dev) at src/CMakeLists.txt:573 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "updaterevision".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by cmbruns** [comment]
This is automatically fixed by others' changes in recent gz3_1.x and gz3_2.x branches
