### ISSUE TITLE
Port to HTC Vive

### ISSUE THREAD

**Issue by cmbruns-hhmi** [cmbruns/gz3doom#121]
...now that I have one.

**Comment by rdldr** [comment]
I just learned that this exists, and I _need_ a Vive port!

**Comment by VRtrout** [comment]
+1 Vive support!

**Comment by Mettanine** [comment]
Would love that, but it would have to implement Teleport and weapons attached to the controller. Sounds non-trivial really...

**Comment by cmbruns-hhmi** [comment]
@Mettanine the phrase "would have to" might be a bit strong. Teleport might not be possible without changing the gameplay dynamics, which I don't want to do. But I'm starting to think "weapon attached to controller" might be workable. But again, that feature is not necessary either, to meet the bar of "as good as the Rift version", which hundreds of people already love, including me. This is my personal project, and I don't need the mass appeal required by those developers whose day jobs depend on those sorts of features. I'm sorry if you won't be able to enjoy it without teleport. I recommend you try the stereoscopic nvidia 3D vision mode, if you can't stomach the classic locomotion model in VR.

**Comment by sigboe** [comment]
@cmbruns-hhmi As a Rift owner with Razer Hydra (supports Vive games) and will be Oculus Touch owner ASAP, I would really appreciate 1:1 tracked weapons. I don't care much for teleportation in retrofitted games.

**Comment by annahowell** [comment]
Will fe||ate for Vive version. No......really.

**Comment by ghost** [comment]
:+1:

**Comment by DemmyDemon** [comment]
As a Vive owner, and a huge fan of roomscale play, I have to say that I'd be perfectly happy and deeply satisfied with "just" WASD-walking while seated.

**Comment by Haczar** [comment]
I am happy with wasd walking BUT I WOULD LOVE TO USE THE CONTROLLER AS THE GUN!!

**Comment by rclough** [comment]
What's the word on this? I'm guessing its pending improvement of your pyopenvr?

**Comment by cmbruns** [comment]
First OpenVR version of gzdoom is now available at https://github.com/cmbruns/gz3doom/releases
Please try it out and give feedback
