### ISSUE TITLE
Import gzdoom 1.x updates

### ISSUE THREAD

**Issue by cmbruns-hhmi** [cmbruns/gz3doom#122]
I'm rather far behind right now. But I just started a branch that looks promising, incorporating the changes after a huge gap in 1.x development before September 2015

**Comment by cmbruns-hhmi** [comment]
One tricky part will be incorporating the somewhat different approach I took to stereo 3D in the upstream gzdoom.

**Comment by cmbruns** [comment]
I got it merged in a branch called gz3_1.x.
Then I quickly copied that to a new branch called gz3_2.x, where I am doing my main development right now.
