### ISSUE TITLE
Smooth only in menus

### ISSUE THREAD

**Issue by driftervr** [cmbruns/gz3doom#144]
Hi Christopher,
First of all, thank you  ! Gz3doom was of one my best VR experience with my DK2.

Now with my CV1 (and a decent rig) , I have judders all the time except in the menus (where rot. AND pos. tracking are very smooth as it should be). It seems that the more monsters are displayed, the more I have judders.
I tried pretty everything (+vid_vsync false, ASW on and off, various WADs, with and without brutal doom...).

Thanks if you could give me a clue !

**Comment by cmbruns** [comment]
Hmm. Sometimes there is judder if the refresh rate of your monitor is lower than the refresh rate of the Oculus Rift. Could that be happening in your case @driftervr ?

**Comment by driftervr** [comment]
Thanks you for your time. Indeed I have a 60 Hz monitor (just in case, I tried @75 Hz but no better results - can't try @90). Also I was wrong : head translation is also jerky in menus (I had to swing my head pretty fast to realize it). Only head rotation when in pause is totally smooth (I guess because of ATW ?).

**Comment by cmbruns-hhmi** [comment]
I think the refresh rate in the menus and title screens is only about 30 Hz, which is the fundamental tic rate in doom. Only during active game play does the display refresh rate rise to the actual hardware rate of the VR headset.

It's possible the game is not able to maintain 90 Hz on your setup. Are you playing a complex mod? Maybe you could adjust the graphics settings to lower the rendering burden.

**Comment by driftervr** [comment]
Ok I just found out that the maps I wanted to play (Brutal Doom 64 and Foursite 4-in-1) were simply too big to be played in VR, despite a powerful PC... Now I feel a bit silly >_<
Thanks again Christopher.
