### ISSUE TITLE
.dll error upon launch.

### ISSUE THREAD

**Issue by formicsapien** [cmbruns/gz3doom#158]
I don't know if this is a problem that is independent of your installer or just my machine.  The only .dll in the folder after install is the openvr one.  No fmodex64, no libmpg, no libsndfile.  It's calling for zlib.dll when I open it but after putting a copy of zlib.dll in the install directory I try to launch it and nothing happens.

I'll try building from the source to see if it still happens...

EDIT: I'm on Windows 10

EDIT2:  Okay, built from source, and I can't get VR_MODE 10 to work.  I tried other vr options, and they work fine (sbs etc.).  I tried both changing it in the console with vr_mode 10 and with the launch option flag -vr_mode 10.  With the launch tag it won't load, when booting it recognizes my vive, but then crashes before the loading bar reachus full.  And with the console nothing happens.  Should I make this a different bug report?

**Comment by cmbruns** [comment]
Thanks for testing this @formicsapien 
That's definitely a defect of the installer that those dlls are absent. This is an important bug to fix here.
When you say "nothing happens" after you copy zlib.dll, what exactly do you mean? 
Is that a 32-bit zlib.dll you copied?

**Comment by cmbruns** [comment]
Probably fixed in revision fba2ac675d3005f712e36d68213a166f4afe587a

**Comment by formicsapien** [comment]
Sorry for not getting you feedback earlier.  Had a personal emergency, and didn't have much free time.  This is fixed as well as the other dll problems, I'll post on my other bug submission.
