### ISSUE TITLE
More required .dll ?

### ISSUE THREAD

**Issue by formicsapien** [cmbruns/gz3doom#160]
Game loads, but when I try to start a game in the menu it crashes w/0.5.1

Error:
"Could not load fluidsynth.dll or libfluidsynth.dll"

This came up both when I just ran it by openeing the exe directly, and when I tried it with the -vr_mode 10 launch option.

Is it must my machine?  Am I missing an inordinate amount of libraries or something?

**Comment by ChristopherJMiller** [comment]
I experienced the same thing, so either we are both missing libraries or it's a bug in the version (using 0.5.1 as well).

**Comment by cmbruns** [comment]
What happens if you set the sound options to something other than fluidsynth before starting the game?
This problem does not happen for me. Perhaps you have fluidsynth installed already somewhere else but it's a 64-bit version?

**Comment by cmbruns** [comment]
Could you please try out release 0.5.2 and tell me whether that works any better? @ChristopherJMiller @formicsapien

**Comment by ChristopherJMiller** [comment]
Works now, thank you

**Comment by cmbruns** [comment]
Awesome. Thanks

**Comment by formicsapien** [comment]
Works for me too, thanks!
