### ISSUE TITLE
[Openvr] Code: C0000005 (Access Violation - tried to read address 000000E0)

### ISSUE THREAD

**Issue by st45244** [cmbruns/gz3doom#162]
[CrashReport.zip](https://github.com/cmbruns/gz3doom/files/1102598/CrashReport.zip)

**Comment by st45244** [comment]
[CrashReport.zip](https://github.com/cmbruns/gz3doom/files/1102560/CrashReport.zip)

**Comment by st45244** [comment]
fixed on version 0.5.2

**Comment by cmbruns** [comment]
Thanks for testing and reporting!

**Comment by cmbruns** [comment]
Fixed in revision c305b25237f1343eadeb1a1d45845513f8e917d1 presumably
