### ISSUE TITLE
Game shows up on moniter, moves with headset, nothing in headset

### ISSUE THREAD

**Issue by MastaFoo** [cmbruns/gz3doom#163]
Hello, I have the latest version, a Vive, Sapphire Nitro+ 480 8GB, FX 8350, 16GB DDR3 RAM, and my problem is as follows:

I boot the game up, enable VR mode, and the game on the monitor splits to SBS3D like it should, and moves with the tracked headset, but in the headset, all i see is black, and my chaperone bounds. It doesnt matter if I use Direct or Extended mode, doesnt matter if i start with the .bat file, and doesnt matter if I start with the Vive turned on or off; the result is the same every time.

**Comment by cmbruns** [comment]
After you quit doom, do you see the Vive home room in the headset? Ori is it still black then?

**Comment by MastaFoo** [comment]
Home/ VR Landing area on closing doom.

**Comment by st45244** [comment]
having same issue headset moves with game headset black. it goes back to steam home when i exit game 
just to add i have xfx ati rx480

**Comment by cmbruns** [comment]
What is your video driver version? @MastaFoo

**Comment by MastaFoo** [comment]
17.5.1

**Comment by gsmsosv** [comment]
I am also experiencing this issue with an R9 390X, driver version 17.4.1. Additionally, once you select a difficulty and start a new game, the headset displays a "hall of mirrors" effect with the chaperone boundaries. This returns to normal upon exiting.

**Comment by cmbruns** [comment]
@MastaFoo @st45244 @gsmsosv Could you please try ViveDoom0.5.4 and report back whether this issue is affected?
https://github.com/cmbruns/gz3doom/releases

**Comment by cmbruns** [comment]
Presumably fixed in revision 5e91f6eeeaff776ab8324aabfccfec159c115043

**Comment by gsmsosv** [comment]
Confirmed, issue is fixed in the latest version! Thanks!

**Comment by MastaFoo** [comment]
Fixed on my end. Thank you for your awesome work.
