### ISSUE TITLE
[OpenVR] Black Screen Enabling vr_mode 10?

### ISSUE THREAD

**Issue by st45244** [cmbruns/gz3doom#164]
htc vive only shows black when enabling vr mode tried different vdeo modes nothing helps.

**Comment by cmbruns** [comment]
This could be the same problem in #163 
What video card do you have?

**Comment by st45244** [comment]
xfx rx480

**Comment by st45244** [comment]
if u want i can try a different video card see if it happens.

**Comment by cmbruns** [comment]
Yes please try another card if it's not too much trouble. The person with the other similar issue also has a card with "480" in it. It might be helpful to know whether that's a coincidence or a true corellation.

**Comment by st45244** [comment]
thats fine i have a nvidia card that i can try + im on vacation so i just have time

**Comment by st45244** [comment]
ok it works with nvidia 750 ti no proplems

**Comment by st45244** [comment]
so it might be problem with the ati side

**Comment by cmbruns** [comment]
That's useful information. Do you happen to know the exact driver version you were using with the AMD card?

**Comment by MastaFoo** [comment]
17.5.1 for me

**Comment by st45244** [comment]
17.6.2

**Comment by st45244** [comment]
anything else u need me 2 try?

**Comment by cmbruns** [comment]
I'm not sure what to try next. Is 17.6.2 the latest driver version?

**Comment by MastaFoo** [comment]
Yes

**Comment by cmbruns** [comment]
To fix bug #165 , I made a fundamental change to the way that the scene is copied to the headset. Maybe we'll get lucky and somehow that change would magically solve this problem too. I'll report back after I put a new release together.

**Comment by MastaFoo** [comment]
Cool beans. I'm off today and my daughter will be with her grandmother later so I'll be able to test it out right away

**Comment by st45244** [comment]
thats fine tnx 4 all ur help.

**Comment by cmbruns** [comment]
@MastaFoo could you please try the latest release 0.5.3 and report back here whether it resolves this problem?
https://github.com/cmbruns/gz3doom/releases

**Comment by st45244** [comment]
45980ec still has the same problem.

**Comment by MastaFoo** [comment]
Issue persists with new version

**Comment by cmbruns** [comment]
That's too bad.  Unfortunately I don't have one of those video boards to test with so I might not solve this right away.

**Comment by st45244** [comment]
im trying older drivers right now so ill see if it was ati fault in this matter.

**Comment by st45244** [comment]
tried Radeon Software Version
16.6.2 still nothing

**Comment by st45244** [comment]
hmmm this one sounds awfully familiar 2 this problem https://github.com/KozGit/DOOM-3-BFG-VR/issues/120

**Comment by MastaFoo** [comment]
@st45244 yes it does I thought the same. Except with DOOM 3 it was the menus that were black and the game itself would show up

**Comment by st45244** [comment]
9fbde6f Still same black screen can see my chaperone walls but nothing else

**Comment by st45244** [comment]
i think ill try another graphics card see if it works on a older ati

**Comment by cmbruns** [comment]
I made a few more changes that I imagine might fix the problem. Please try prerelease 0.5.5
https://github.com/cmbruns/gz3doom/releases/tag/vivedoom0.5.5

**Comment by st45244** [comment]
Yes it works!!!!! thank u!!!!

**Comment by st45244** [comment]
it works!!!!

**Comment by cmbruns** [comment]
Awesome!

**Comment by st45244** [comment]
as of  d608665 it fixed it
