### ISSUE TITLE
Brightness, contrast and gamma changes are not reflected on HMD.

### ISSUE THREAD

**Issue by wadim-al** [cmbruns/gz3doom#165]
When I change the brightness, contrast, and gamma the VR output is not changing at all. Only the picture on my monitor changes.
I'm using RiftCat in SteamVR mode and the picture is too dark for me.

**Comment by cmbruns** [comment]
Verified. This probably needs to be handled in OpenVREyePose::submitFrame(), and it needs to use the gamma correction found in FGLRenderer::DrawPresentTexture()

**Comment by cmbruns** [comment]
Fixed in revision 45980ec73a21c4daab40c19bd03b986536e662f3
This should work in the next release.

**Comment by cmbruns** [comment]
@wadim-al Could you please try the new release, version 0.5.3, I just now uploaded, and report back whether it fixes the problem?
https://github.com/cmbruns/gz3doom/releases

**Comment by wadim-al** [comment]
All three: brightness, contrast, and gamma settings are working now. Thanks!
