### ISSUE TITLE
Adjusting the size of some fonts

### ISSUE THREAD

**Issue by Hoodad** [cmbruns/gz3doom#171]
The fonts/icons for ammo and health are good in terms of size. But the font in the upper left corner together with the notifications that appear are far too small.

**Comment by cmbruns** [comment]
Type in the console (`)
CON_SCALETEXT 3
CON_SCALE 2

https://zdoom.org/wiki/CVARs:Messages

**Comment by cmbruns** [comment]
More generally, play with the settings in the options menu:
Menu[ESC]->Options->Hud Options->Scaling Options
