### ISSUE TITLE
Doom E1M4 render error

### ISSUE THREAD

**Issue by ckbruns** [cmbruns/gz3doom#40]
1.8.6_g
Facing West

![screenshot_doom_20140601_150803](https://cloud.githubusercontent.com/assets/5731752/3142476/72496964-e9c0-11e3-8bc2-2ad8ceed4035.png)
![screenshot_doom_20140601_150820](https://cloud.githubusercontent.com/assets/5731752/3142477/7b547562-e9c0-11e3-80ab-55a149aa2a0e.png)

**Comment by cmbruns-hhmi** [comment]
I wonder whether rendering the left eye twice would be an enlightening test.

**Comment by cmbruns** [comment]
* Rendering the left eye twice does NOT help
* Reactivating the call to gl_drawinfo->DrawUnhandledMissingTextures() DOES unify the appearance of the left and right eyes for this glitch. Unfortunately, doing so also reactivates other display bugs I had thought resolved in the nearby doors, and probably issue #27.

**Comment by cmbruns** [comment]
This glitch, as it stands, is the lesser of two evils for the time being. Until I can figure out how to correctly call DrawUnhandledMissingTextures() twice in the same pass, without causing display artifacts, I'm leaving this as is.

**Comment by cmbruns** [comment]
Fixed in revision a88130b0bf275f263b2e6a29b7b1387947270dc5
