### ISSUE TITLE
Wrong weapon position in nonRift stereo (vr_mode 4 and 3)

### ISSUE THREAD

**Issue by the-mrC** [cmbruns/gz3doom#51]
Current weapons placement in nonRift modes (vr_mode 4 and 3) on 3Dscreen is wrong and disturbing. Please can you move weapons down to bottom of the screen in vr_mode 4 and 3 (weapons should appear on the same place as in vr_mode 0, 1 and 2 just in stereo).

**Comment by cmbruns** [comment]
Weapon positions will be fixed in GZ3Doom release 1.8.6_k

**Comment by cmbruns** [comment]
Fixed in revision d151993da4fd32643d21f6b140ecf41b25137666
