### ISSUE TITLE
Incorporate Status, Menus, Console, Transitions, etc. into each eye view for NonRift vr_mode 4 (and 3)

### ISSUE THREAD

**Issue by the-mrC** [cmbruns/gz3doom#52]
Menu, HUD, map, texts, crosshair and other 2D efects in nonRift Stereo are (in vr_mode 4 and 3) visualised in mono above the stereo scene! 

It seems that this was already been fixed for Rift mode long time ago (https://github.com/cmbruns/gz3doom/issues/2)! 

Can it be fixed for nonRift (vr_mode 4 and 3) stereo modes too?

Right now is this problem partly covered by https://github.com/cmbruns/gz3doom/issues/24, but it isnt just problem of HUD, its also problem of menu, maps, crosshair, etc... !

**Comment by cmbruns** [comment]
Fixed in fd4206fadc14a905fb2cae9459438c4f141fec3e
