### ISSUE TITLE
nonRift vr_mode 4 and 3 weapon cosmetic problem

### ISSUE THREAD

**Issue by the-mrC** [cmbruns/gz3doom#54]
vr_mode 4 and 3 needs bigger weapons, while for Rift is smaller size of weapons great (https://github.com/cmbruns/gz3doom/issues/1), its not so great for nonRift stereo with vr_mode 4 and 3, Its nothing serious but I think its worth mentioning.

**Comment by cmbruns** [comment]
Fixed in revision d151993da4fd32643d21f6b140ecf41b25137666
