### ISSUE TITLE
Create shortcuts for Rift mode on monitor1, monitor2, etc.

### ISSUE THREAD

**Issue by cmbruns-hhmi** [cmbruns/gz3doom#60]

**Comment by cmbruns** [comment]
Maybe a .bat file would be easier than a .lnk file.
LNK trick is here: http://stackoverflow.com/questions/1169556/making-a-windows-shortcut-start-relative-to-where-the-folder-is

**Comment by cmbruns** [comment]
TODO - allow drag and drop of wads onto .bat file

**Comment by cmbruns** [comment]
Bat file links on Windows will be in GZ3Doom version 1.8.6_k

**Comment by cmbruns** [comment]
Fixed in revision d3834b956c540b30ee57ebb5c611d04602dea3c8
