### ISSUE TITLE
Turn off mouse smoothing in oculardium_optimosa

### ISSUE THREAD

**Issue by cmbruns-hhmi** [cmbruns/gz3doom#67]

**Comment by cmbruns-hhmi** [comment]
https://forums.oculus.com/viewtopic.php?f=42&t=4743&start=120

**Comment by cmbruns** [comment]
Fixed in revision d913eaf00a8294363f31916e2dff99a32e2b155e

**Comment by cmbruns** [comment]
Exact comment was
https://forums.oculus.com/viewtopic.php?f=42&t=4743&start=120#p262177
