### ISSUE TITLE
Make vr_hud_scale and vr_weapon_scale larger, and in units of fov degrees

### ISSUE THREAD

**Issue by cmbruns-hhmi** [cmbruns/gz3doom#68]

**Comment by cmbruns** [comment]
I kept the scale the same on vr_hud_scale, for backwards compatibility.
There is no vr_weapon_scale, but I did modify so vr_weapon_height gives an angular offset to the VR weapon location, in degrees.
Fixed in revision c012b04e6933d822a680287ad35a520608bb3387
