### ISSUE TITLE
sdk warping looks terrible on DK1

### ISSUE THREAD

**Issue by cmbruns** [cmbruns/gz3doom#72]
large lateral offset.
1280 vs 1920 somehow?

**Comment by cmbruns** [comment]
![screenshot_doom_20150419_141028](https://cloud.githubusercontent.com/assets/2649705/7220638/04731472-e69e-11e4-9a09-36fa397f19f8.png)

Could it be the projection matrix?

**Comment by cmbruns** [comment]
Probably not projection matrix, because manual projection matrix calculation yields a similar result.

**Comment by cmbruns** [comment]
![screenshot_doom_20150419_143431](https://cloud.githubusercontent.com/assets/2649705/7220757/4258c0b8-e6a1-11e4-85b8-a57bb958c3ce.png)

Client warp for comparison

**Comment by cmbruns** [comment]
To review, using similar viewpoints:

Unwarped:
![screenshot_doom_20150419_160757](https://cloud.githubusercontent.com/assets/2649705/7221148/6049108e-e6ae-11e4-94ed-d523e363af02.png)

Client warped:
![screenshot_doom_20150419_160639](https://cloud.githubusercontent.com/assets/2649705/7221149/63d9cd56-e6ae-11e4-88ef-4ab7cc788aa1.png)

SDK warped:
![screenshot_doom_20150419_160515](https://cloud.githubusercontent.com/assets/2649705/7221154/66a7ca10-e6ae-11e4-90bf-d1174923f24a.png)

**Comment by cmbruns** [comment]
On second look, it seems that sdk warped view in the previous comment is supposed to be looking toward the pool. But the HUD is placed too far to the left. So there is some sort of viewport problem before the warping is applied.

**Comment by cmbruns-hhmi** [comment]
Things to try
* Try using SDK projection matrix with client warping.
* Try using non-transpose version of projection matrix
* Try using SDK 0.4.4 instead of 0.5.0.1 (remember to disable health&safety...)

**Comment by cmbruns-hhmi** [comment]
* Try uninstalling and reinstalling 0.5.0.1

**Comment by cmbruns** [comment]
Still looks bad on virtual (debug) DK1 when linked with SDK 0.4.4, and no Oculus Runtime nor driver installed on the computer (uninstalled first and rebooted).

**Comment by cmbruns** [comment]
OK. The left eye view was correct, but the right eye view was wrong, because I was using the left-eye projection matrix for both eyes. Further, the HUD and weapon sprite need to be adjusted to account for the asymmetric eye position.

**Comment by cmbruns** [comment]
Fixed in revision f44488105413bd78b47bec4a4eba564d46481733
